# required setting at .gitignore
# https://velog.io/@zhyun/spring-boot-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-git-%EC%97%85%EB%A1%9C%EB%93%9C-%EC%8B%9Capi-key-%EB%B0%8F-db-%EC%A0%91%EC%86%8D%EC%A0%95%EB%B3%B4-%EC%88%A8%EA%B8%B0%EA%B8%B0

spring:
  datasource:
    url: #
    username: #
    password: #
